# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-13 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190213_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='date_of_publication',
            field=models.DateField(null=True),
        ),
    ]
